In [47]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from  sklearn.model_selection import KFold
from  sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer

In [92]:
df=pd.read_csv('mail_data.csv')
df.head()

  Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [93]:
encoder=LabelEncoder()
df['Category']=encoder.fit_transform(df['Category'])
df

      Category                                            Message
0            0  Go until jurong point, crazy.. Available only ...
1            0                      Ok lar... Joking wif u oni...
2            1  Free entry in 2 a wkly comp to win FA Cup fina...
3            0  U dun say so early hor... U c already then say...
4            0  Nah I don't think he goes to usf, he lives aro...
...        ...                                                ...
5567         1  This is the 2nd time we have tried 2 contact u...
5568         0               Will ü b going to esplanade fr home?
5569         0  Pity, * was in mood for that. So...any other s...
5570         0  The guy did some bitching but I acted like i'd...
5571         0                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [ ]:
x = df['Message']
y = df['Category']


vectorizer = TfidfVectorizer(stop_words='english')
x_vectorized = vectorizer.fit_transform(x)


model2 = LogisticRegression(max_iter=1000)
kf = KFold(n_splits=5, shuffle=True, random_state=42)


for train_idx, test_idx in kf.split(x_vectorized):
    x_train, x_test = x_vectorized[train_idx], x_vectorized[test_idx]
    y_train, y_test = y.iloc[train_idx], y.iloc[test_idx]   
    model2.fit(x_train, y_train)
    score = model2.score(x_test, y_test)
    
    print(score)




model2.fit(x_vectorized, y)


test = ["you have credited with 100 rupees"]
test_converted = vectorizer.transform(test)
result=model2.predict(test_converted)
if result==1:
    print("Spam !")
elif result==0:
    print("Not Spam !")
else:
    print("Error")

0.95695067264574
0.9524663677130045
0.9578096947935368
0.9497307001795332
0.9470377019748654
Not Spam !